export default interface mahasiswaType {
  nim: string,
  password: string,
  nik: string,
  nama: string,
  prodi: string,
  angkatan: string,
  jenis_kelamin: string,
  tempat_lahir: string,
  tanggal_lahir: string,
  agama: string,
  no_hp: string,
  email: string,
  jalur_masuk: string,
  alamat: string,
  provinsi: string,
  kota: string,
  kecamatan: string,
}